chore: updated verida lib.
verida/markdown-notes-demo pull request #103
Opened 2022-02-28 02:54 UTC by cmcWebCode40

- @verida/account-web-vault > 1.1.9
 - @verida/client-ts > 1.1.12
#102

2022-02-28 21:16 UTC, nick-verida requested changes
One minor change

2022-02-28 21:16 UTC, nick-verida commented on .env
> +REACT_APP_VERIDA_TESTNET_DEFAULT_SERVER=https://db.testnet.verida.io:5002
Is this needed? Remove if not

2022-03-01 05:46 UTC, cmcWebCode40 commented on .env
> +REACT_APP_VERIDA_TESTNET_DEFAULT_SERVER=https://db.testnet.verida.io:5002
i have removed unused env

2022-03-02 22:51 UTC, nick-verida approved these changes
looks good. Merging

2022-03-02 22:51 UTC, merged